dbMemo "SQL" ="SELECT qExport_Events.Admin_Unit_Code, qExport_Events.Sub_Unit_Code, qExport_Eve"
    "nts.Site_Name, qExport_Events.Plot_Name, qExport_Events.Location_Type, qExport_E"
    "vents.Year, qExport_Events.Date, qExport_Events.Start_Time, qExport_Events.End_T"
    "ime, qExport_Events.Observer, qExport_Events.Visit, qExportFieldData.Interval_Le"
    "ngth, qExportFieldData.ID_Method, qExportFieldData.Distance, qExportFieldData.Fl"
    "yover_Observed, qExportFieldData.Sex, qExportFieldData.Common_Name, qExportField"
    "Data.Scientific_Name, qExportFieldData.AcceptedTSN, qExportFieldData.NPSTaxonCod"
    "e, qExportFieldData.AOU_Code, qExportFieldData.PIF_Watchlist_Status, qExportFiel"
    "dData.Regional_Stewardship_Status, qExport_Event_Details.Temperature, qExport_Ev"
    "ent_Details.Humidity, qExport_Event_Details.Sky, qExport_Event_Details.Wind, qEx"
    "port_Event_Details.Disturbance, qExportFieldData.Initial_Three_Min_Cnt\015\012FR"
    "OM (qExport_Events LEFT JOIN qExportFieldData ON qExport_Events.Event_ID = qExpo"
    "rtFieldData.Event_ID) LEFT JOIN qExport_Event_Details ON qExport_Events.Event_ID"
    " = qExport_Event_Details.Event_ID\015\012WHERE (((qExport_Events.Admin_Unit_Code"
    ") = \"ANTI\") AND ((Year) Like \"*\"));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
